### ISSUE TITLE
stroke encoding

### ISSUE THREAD

**Issue by clscy** [JinshanZeng/StrokeGAN#2]
Hi, can you provide stroke encoding dataset of chinese?Thank you .

**Comment by JinshanZeng** [comment]
Sure, we will release our dataset soon. Please find it later from the
github link.

**Comment by clscy** [comment]
Very Thanks. And I have a another question, how to set a reasonable param named parameter_label to compute loss_D in backward_D_basic, how to set a reasonable value?Thank you.
