### ISSUE TITLE
what is parameter_label?

### ISSUE THREAD

**Issue by 21toanyone-pro** [JinshanZeng/StrokeGAN#6]
cycle_gan_model.py

line 153 

loss_D = 0.5*(loss_D_real+parameter_label*loss_D_real_label) + (loss_D_fake+parameter_label*loss_D_fake_label)* 0.5

what is parameter_label??

**Comment by Yonglin5170** [comment]
Hello, maybe it is stroke encoding penalty I think. In this paper, the value is 0.18, but I got terrible results.

**Comment by 21toanyone-pro** [comment]
thanks
